/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthTokens
 */
export interface AuthTokens {
    /**
     * 
     * @type {string}
     * @memberof AuthTokens
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokens
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the AuthTokens interface.
 */
export function instanceOfAuthTokens(value: object): value is AuthTokens {
    return true;
}

export function AuthTokensFromJSON(json: any): AuthTokens {
    return AuthTokensFromJSONTyped(json, false);
}

export function AuthTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokens {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function AuthTokensToJSON(json: any): AuthTokens {
    return AuthTokensToJSONTyped(json, false);
}

export function AuthTokensToJSONTyped(value?: AuthTokens | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

