/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecommendWorksResponse } from './RecommendWorksResponse';
import {
    RecommendWorksResponseFromJSON,
    RecommendWorksResponseFromJSONTyped,
    RecommendWorksResponseToJSON,
    RecommendWorksResponseToJSONTyped,
} from './RecommendWorksResponse';

/**
 * 
 * @export
 * @interface CustomResponseBodyRecommendWorksResponse
 */
export interface CustomResponseBodyRecommendWorksResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomResponseBodyRecommendWorksResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomResponseBodyRecommendWorksResponse
     */
    msg?: string;
    /**
     * 
     * @type {RecommendWorksResponse}
     * @memberof CustomResponseBodyRecommendWorksResponse
     */
    data?: RecommendWorksResponse;
}

/**
 * Check if a given object implements the CustomResponseBodyRecommendWorksResponse interface.
 */
export function instanceOfCustomResponseBodyRecommendWorksResponse(value: object): value is CustomResponseBodyRecommendWorksResponse {
    return true;
}

export function CustomResponseBodyRecommendWorksResponseFromJSON(json: any): CustomResponseBodyRecommendWorksResponse {
    return CustomResponseBodyRecommendWorksResponseFromJSONTyped(json, false);
}

export function CustomResponseBodyRecommendWorksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomResponseBodyRecommendWorksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : RecommendWorksResponseFromJSON(json['data']),
    };
}

export function CustomResponseBodyRecommendWorksResponseToJSON(json: any): CustomResponseBodyRecommendWorksResponse {
    return CustomResponseBodyRecommendWorksResponseToJSONTyped(json, false);
}

export function CustomResponseBodyRecommendWorksResponseToJSONTyped(value?: CustomResponseBodyRecommendWorksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': RecommendWorksResponseToJSON(value['data']),
    };
}

