/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModifyMyWorkResponse } from './ModifyMyWorkResponse';
import {
    ModifyMyWorkResponseFromJSON,
    ModifyMyWorkResponseFromJSONTyped,
    ModifyMyWorkResponseToJSON,
    ModifyMyWorkResponseToJSONTyped,
} from './ModifyMyWorkResponse';

/**
 * 
 * @export
 * @interface CustomResponseBodyModifyMyWorkResponse
 */
export interface CustomResponseBodyModifyMyWorkResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomResponseBodyModifyMyWorkResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomResponseBodyModifyMyWorkResponse
     */
    msg?: string;
    /**
     * 
     * @type {ModifyMyWorkResponse}
     * @memberof CustomResponseBodyModifyMyWorkResponse
     */
    data?: ModifyMyWorkResponse;
}

/**
 * Check if a given object implements the CustomResponseBodyModifyMyWorkResponse interface.
 */
export function instanceOfCustomResponseBodyModifyMyWorkResponse(value: object): value is CustomResponseBodyModifyMyWorkResponse {
    return true;
}

export function CustomResponseBodyModifyMyWorkResponseFromJSON(json: any): CustomResponseBodyModifyMyWorkResponse {
    return CustomResponseBodyModifyMyWorkResponseFromJSONTyped(json, false);
}

export function CustomResponseBodyModifyMyWorkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomResponseBodyModifyMyWorkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : ModifyMyWorkResponseFromJSON(json['data']),
    };
}

export function CustomResponseBodyModifyMyWorkResponseToJSON(json: any): CustomResponseBodyModifyMyWorkResponse {
    return CustomResponseBodyModifyMyWorkResponseToJSONTyped(json, false);
}

export function CustomResponseBodyModifyMyWorkResponseToJSONTyped(value?: CustomResponseBodyModifyMyWorkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': ModifyMyWorkResponseToJSON(value['data']),
    };
}

