/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetAirQualityResponse } from '../models/GetAirQualityResponse';

export class CustomResponseBodyGetAirQualityResponse {
    'code'?: number;
    'msg'?: string;
    'data'?: GetAirQualityResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "GetAirQualityResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomResponseBodyGetAirQualityResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
