/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegisterMyWorkResponse } from './RegisterMyWorkResponse';
import {
    RegisterMyWorkResponseFromJSON,
    RegisterMyWorkResponseFromJSONTyped,
    RegisterMyWorkResponseToJSON,
    RegisterMyWorkResponseToJSONTyped,
} from './RegisterMyWorkResponse';

/**
 * 
 * @export
 * @interface CustomResponseBodyRegisterMyWorkResponse
 */
export interface CustomResponseBodyRegisterMyWorkResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomResponseBodyRegisterMyWorkResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomResponseBodyRegisterMyWorkResponse
     */
    msg?: string;
    /**
     * 
     * @type {RegisterMyWorkResponse}
     * @memberof CustomResponseBodyRegisterMyWorkResponse
     */
    data?: RegisterMyWorkResponse;
}

/**
 * Check if a given object implements the CustomResponseBodyRegisterMyWorkResponse interface.
 */
export function instanceOfCustomResponseBodyRegisterMyWorkResponse(value: object): value is CustomResponseBodyRegisterMyWorkResponse {
    return true;
}

export function CustomResponseBodyRegisterMyWorkResponseFromJSON(json: any): CustomResponseBodyRegisterMyWorkResponse {
    return CustomResponseBodyRegisterMyWorkResponseFromJSONTyped(json, false);
}

export function CustomResponseBodyRegisterMyWorkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomResponseBodyRegisterMyWorkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : RegisterMyWorkResponseFromJSON(json['data']),
    };
}

export function CustomResponseBodyRegisterMyWorkResponseToJSON(json: any): CustomResponseBodyRegisterMyWorkResponse {
    return CustomResponseBodyRegisterMyWorkResponseToJSONTyped(json, false);
}

export function CustomResponseBodyRegisterMyWorkResponseToJSONTyped(value?: CustomResponseBodyRegisterMyWorkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': RegisterMyWorkResponseToJSON(value['data']),
    };
}

