/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetFcstRisk } from './GetFcstRisk';
import {
    GetFcstRiskFromJSON,
    GetFcstRiskFromJSONTyped,
    GetFcstRiskToJSON,
    GetFcstRiskToJSONTyped,
} from './GetFcstRisk';

/**
 * 
 * @export
 * @interface CustomResponseBodyGetFcstRisk
 */
export interface CustomResponseBodyGetFcstRisk {
    /**
     * 
     * @type {number}
     * @memberof CustomResponseBodyGetFcstRisk
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomResponseBodyGetFcstRisk
     */
    msg?: string;
    /**
     * 
     * @type {GetFcstRisk}
     * @memberof CustomResponseBodyGetFcstRisk
     */
    data?: GetFcstRisk;
}

/**
 * Check if a given object implements the CustomResponseBodyGetFcstRisk interface.
 */
export function instanceOfCustomResponseBodyGetFcstRisk(value: object): value is CustomResponseBodyGetFcstRisk {
    return true;
}

export function CustomResponseBodyGetFcstRiskFromJSON(json: any): CustomResponseBodyGetFcstRisk {
    return CustomResponseBodyGetFcstRiskFromJSONTyped(json, false);
}

export function CustomResponseBodyGetFcstRiskFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomResponseBodyGetFcstRisk {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : GetFcstRiskFromJSON(json['data']),
    };
}

export function CustomResponseBodyGetFcstRiskToJSON(json: any): CustomResponseBodyGetFcstRisk {
    return CustomResponseBodyGetFcstRiskToJSONTyped(json, false);
}

export function CustomResponseBodyGetFcstRiskToJSONTyped(value?: CustomResponseBodyGetFcstRisk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': GetFcstRiskToJSON(value['data']),
    };
}

