/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetWeatherBriefing } from './GetWeatherBriefing';
import {
    GetWeatherBriefingFromJSON,
    GetWeatherBriefingFromJSONTyped,
    GetWeatherBriefingToJSON,
    GetWeatherBriefingToJSONTyped,
} from './GetWeatherBriefing';

/**
 * 
 * @export
 * @interface CustomResponseBodyGetWeatherBriefing
 */
export interface CustomResponseBodyGetWeatherBriefing {
    /**
     * 
     * @type {number}
     * @memberof CustomResponseBodyGetWeatherBriefing
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomResponseBodyGetWeatherBriefing
     */
    msg?: string;
    /**
     * 
     * @type {GetWeatherBriefing}
     * @memberof CustomResponseBodyGetWeatherBriefing
     */
    data?: GetWeatherBriefing;
}

/**
 * Check if a given object implements the CustomResponseBodyGetWeatherBriefing interface.
 */
export function instanceOfCustomResponseBodyGetWeatherBriefing(value: object): value is CustomResponseBodyGetWeatherBriefing {
    return true;
}

export function CustomResponseBodyGetWeatherBriefingFromJSON(json: any): CustomResponseBodyGetWeatherBriefing {
    return CustomResponseBodyGetWeatherBriefingFromJSONTyped(json, false);
}

export function CustomResponseBodyGetWeatherBriefingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomResponseBodyGetWeatherBriefing {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : GetWeatherBriefingFromJSON(json['data']),
    };
}

export function CustomResponseBodyGetWeatherBriefingToJSON(json: any): CustomResponseBodyGetWeatherBriefing {
    return CustomResponseBodyGetWeatherBriefingToJSONTyped(json, false);
}

export function CustomResponseBodyGetWeatherBriefingToJSONTyped(value?: CustomResponseBodyGetWeatherBriefing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': GetWeatherBriefingToJSON(value['data']),
    };
}

