/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomResponseBodyVoid
 */
export interface CustomResponseBodyVoid {
    /**
     * 
     * @type {number}
     * @memberof CustomResponseBodyVoid
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomResponseBodyVoid
     */
    msg?: string;
    /**
     * 
     * @type {object}
     * @memberof CustomResponseBodyVoid
     */
    data?: object;
}

/**
 * Check if a given object implements the CustomResponseBodyVoid interface.
 */
export function instanceOfCustomResponseBodyVoid(value: object): value is CustomResponseBodyVoid {
    return true;
}

export function CustomResponseBodyVoidFromJSON(json: any): CustomResponseBodyVoid {
    return CustomResponseBodyVoidFromJSONTyped(json, false);
}

export function CustomResponseBodyVoidFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomResponseBodyVoid {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function CustomResponseBodyVoidToJSON(json: any): CustomResponseBodyVoid {
    return CustomResponseBodyVoidToJSONTyped(json, false);
}

export function CustomResponseBodyVoidToJSONTyped(value?: CustomResponseBodyVoid | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'],
    };
}

