/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetMyWorksOfTodayResponse } from './GetMyWorksOfTodayResponse';
import {
    GetMyWorksOfTodayResponseFromJSON,
    GetMyWorksOfTodayResponseFromJSONTyped,
    GetMyWorksOfTodayResponseToJSON,
    GetMyWorksOfTodayResponseToJSONTyped,
} from './GetMyWorksOfTodayResponse';

/**
 * 
 * @export
 * @interface CustomResponseBodyListGetMyWorksOfTodayResponse
 */
export interface CustomResponseBodyListGetMyWorksOfTodayResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomResponseBodyListGetMyWorksOfTodayResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomResponseBodyListGetMyWorksOfTodayResponse
     */
    msg?: string;
    /**
     * 
     * @type {Array<GetMyWorksOfTodayResponse>}
     * @memberof CustomResponseBodyListGetMyWorksOfTodayResponse
     */
    data?: Array<GetMyWorksOfTodayResponse>;
}

/**
 * Check if a given object implements the CustomResponseBodyListGetMyWorksOfTodayResponse interface.
 */
export function instanceOfCustomResponseBodyListGetMyWorksOfTodayResponse(value: object): value is CustomResponseBodyListGetMyWorksOfTodayResponse {
    return true;
}

export function CustomResponseBodyListGetMyWorksOfTodayResponseFromJSON(json: any): CustomResponseBodyListGetMyWorksOfTodayResponse {
    return CustomResponseBodyListGetMyWorksOfTodayResponseFromJSONTyped(json, false);
}

export function CustomResponseBodyListGetMyWorksOfTodayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomResponseBodyListGetMyWorksOfTodayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GetMyWorksOfTodayResponseFromJSON)),
    };
}

export function CustomResponseBodyListGetMyWorksOfTodayResponseToJSON(json: any): CustomResponseBodyListGetMyWorksOfTodayResponse {
    return CustomResponseBodyListGetMyWorksOfTodayResponseToJSONTyped(json, false);
}

export function CustomResponseBodyListGetMyWorksOfTodayResponseToJSONTyped(value?: CustomResponseBodyListGetMyWorksOfTodayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GetMyWorksOfTodayResponseToJSON)),
    };
}

