/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetWeatherGraph } from './GetWeatherGraph';
import {
    GetWeatherGraphFromJSON,
    GetWeatherGraphFromJSONTyped,
    GetWeatherGraphToJSON,
    GetWeatherGraphToJSONTyped,
} from './GetWeatherGraph';

/**
 * 
 * @export
 * @interface CustomResponseBodyGetWeatherGraph
 */
export interface CustomResponseBodyGetWeatherGraph {
    /**
     * 
     * @type {number}
     * @memberof CustomResponseBodyGetWeatherGraph
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomResponseBodyGetWeatherGraph
     */
    msg?: string;
    /**
     * 
     * @type {GetWeatherGraph}
     * @memberof CustomResponseBodyGetWeatherGraph
     */
    data?: GetWeatherGraph;
}

/**
 * Check if a given object implements the CustomResponseBodyGetWeatherGraph interface.
 */
export function instanceOfCustomResponseBodyGetWeatherGraph(value: object): value is CustomResponseBodyGetWeatherGraph {
    return true;
}

export function CustomResponseBodyGetWeatherGraphFromJSON(json: any): CustomResponseBodyGetWeatherGraph {
    return CustomResponseBodyGetWeatherGraphFromJSONTyped(json, false);
}

export function CustomResponseBodyGetWeatherGraphFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomResponseBodyGetWeatherGraph {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : GetWeatherGraphFromJSON(json['data']),
    };
}

export function CustomResponseBodyGetWeatherGraphToJSON(json: any): CustomResponseBodyGetWeatherGraph {
    return CustomResponseBodyGetWeatherGraphToJSONTyped(json, false);
}

export function CustomResponseBodyGetWeatherGraphToJSONTyped(value?: CustomResponseBodyGetWeatherGraph | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': GetWeatherGraphToJSON(value['data']),
    };
}

