/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetWeatherCondition } from './GetWeatherCondition';
import {
    GetWeatherConditionFromJSON,
    GetWeatherConditionFromJSONTyped,
    GetWeatherConditionToJSON,
    GetWeatherConditionToJSONTyped,
} from './GetWeatherCondition';

/**
 * 
 * @export
 * @interface CustomResponseBodyGetWeatherCondition
 */
export interface CustomResponseBodyGetWeatherCondition {
    /**
     * 
     * @type {number}
     * @memberof CustomResponseBodyGetWeatherCondition
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomResponseBodyGetWeatherCondition
     */
    msg?: string;
    /**
     * 
     * @type {GetWeatherCondition}
     * @memberof CustomResponseBodyGetWeatherCondition
     */
    data?: GetWeatherCondition;
}

/**
 * Check if a given object implements the CustomResponseBodyGetWeatherCondition interface.
 */
export function instanceOfCustomResponseBodyGetWeatherCondition(value: object): value is CustomResponseBodyGetWeatherCondition {
    return true;
}

export function CustomResponseBodyGetWeatherConditionFromJSON(json: any): CustomResponseBodyGetWeatherCondition {
    return CustomResponseBodyGetWeatherConditionFromJSONTyped(json, false);
}

export function CustomResponseBodyGetWeatherConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomResponseBodyGetWeatherCondition {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : GetWeatherConditionFromJSON(json['data']),
    };
}

export function CustomResponseBodyGetWeatherConditionToJSON(json: any): CustomResponseBodyGetWeatherCondition {
    return CustomResponseBodyGetWeatherConditionToJSONTyped(json, false);
}

export function CustomResponseBodyGetWeatherConditionToJSONTyped(value?: CustomResponseBodyGetWeatherCondition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': GetWeatherConditionToJSON(value['data']),
    };
}

