/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthTokens } from './AuthTokens';
import {
    AuthTokensFromJSON,
    AuthTokensFromJSONTyped,
    AuthTokensToJSON,
    AuthTokensToJSONTyped,
} from './AuthTokens';

/**
 * 
 * @export
 * @interface CustomResponseBodyAuthTokens
 */
export interface CustomResponseBodyAuthTokens {
    /**
     * 
     * @type {number}
     * @memberof CustomResponseBodyAuthTokens
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomResponseBodyAuthTokens
     */
    msg?: string;
    /**
     * 
     * @type {AuthTokens}
     * @memberof CustomResponseBodyAuthTokens
     */
    data?: AuthTokens;
}

/**
 * Check if a given object implements the CustomResponseBodyAuthTokens interface.
 */
export function instanceOfCustomResponseBodyAuthTokens(value: object): value is CustomResponseBodyAuthTokens {
    return true;
}

export function CustomResponseBodyAuthTokensFromJSON(json: any): CustomResponseBodyAuthTokens {
    return CustomResponseBodyAuthTokensFromJSONTyped(json, false);
}

export function CustomResponseBodyAuthTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomResponseBodyAuthTokens {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : AuthTokensFromJSON(json['data']),
    };
}

export function CustomResponseBodyAuthTokensToJSON(json: any): CustomResponseBodyAuthTokens {
    return CustomResponseBodyAuthTokensToJSONTyped(json, false);
}

export function CustomResponseBodyAuthTokensToJSONTyped(value?: CustomResponseBodyAuthTokens | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': AuthTokensToJSON(value['data']),
    };
}

