/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteMyWorkRequest
 */
export interface DeleteMyWorkRequest {
    /**
     * 
     * @type {number}
     * @memberof DeleteMyWorkRequest
     */
    myWorkId: number;
}

/**
 * Check if a given object implements the DeleteMyWorkRequest interface.
 */
export function instanceOfDeleteMyWorkRequest(value: object): value is DeleteMyWorkRequest {
    if (!('myWorkId' in value) || value['myWorkId'] === undefined) return false;
    return true;
}

export function DeleteMyWorkRequestFromJSON(json: any): DeleteMyWorkRequest {
    return DeleteMyWorkRequestFromJSONTyped(json, false);
}

export function DeleteMyWorkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMyWorkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'myWorkId': json['myWorkId'],
    };
}

export function DeleteMyWorkRequestToJSON(json: any): DeleteMyWorkRequest {
    return DeleteMyWorkRequestToJSONTyped(json, false);
}

export function DeleteMyWorkRequestToJSONTyped(value?: DeleteMyWorkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'myWorkId': value['myWorkId'],
    };
}

