/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetAirQualityResponse {
    'pm10Value'?: number;
    'pm10Grade'?: number;
    'pm25Value'?: number;
    'pm25Grade'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pm10Value",
            "baseName": "pm10Value",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pm10Grade",
            "baseName": "pm10Grade",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pm25Value",
            "baseName": "pm25Value",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pm25Grade",
            "baseName": "pm25Grade",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return GetAirQualityResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
