/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WeatherRiskDto } from './WeatherRiskDto';
import {
    WeatherRiskDtoFromJSON,
    WeatherRiskDtoFromJSONTyped,
    WeatherRiskDtoToJSON,
    WeatherRiskDtoToJSONTyped,
} from './WeatherRiskDto';

/**
 * 
 * @export
 * @interface GetFcstRisk
 */
export interface GetFcstRisk {
    /**
     * 
     * @type {Array<WeatherRiskDto>}
     * @memberof GetFcstRisk
     */
    items?: Array<WeatherRiskDto>;
}

/**
 * Check if a given object implements the GetFcstRisk interface.
 */
export function instanceOfGetFcstRisk(value: object): value is GetFcstRisk {
    return true;
}

export function GetFcstRiskFromJSON(json: any): GetFcstRisk {
    return GetFcstRiskFromJSONTyped(json, false);
}

export function GetFcstRiskFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFcstRisk {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(WeatherRiskDtoFromJSON)),
    };
}

export function GetFcstRiskToJSON(json: any): GetFcstRisk {
    return GetFcstRiskToJSONTyped(json, false);
}

export function GetFcstRiskToJSONTyped(value?: GetFcstRisk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(WeatherRiskDtoToJSON)),
    };
}

