/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMyWorksOfTodayResponse
 */
export interface GetMyWorksOfTodayResponse {
    /**
     * 
     * @type {number}
     * @memberof GetMyWorksOfTodayResponse
     */
    myWorkId?: number;
    /**
     * 
     * @type {string}
     * @memberof GetMyWorksOfTodayResponse
     */
    myCropName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMyWorksOfTodayResponse
     */
    myWorkName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMyWorksOfTodayResponse
     */
    workTime?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMyWorksOfTodayResponse
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMyWorksOfTodayResponse
     */
    endTime?: string;
}

/**
 * Check if a given object implements the GetMyWorksOfTodayResponse interface.
 */
export function instanceOfGetMyWorksOfTodayResponse(value: object): value is GetMyWorksOfTodayResponse {
    return true;
}

export function GetMyWorksOfTodayResponseFromJSON(json: any): GetMyWorksOfTodayResponse {
    return GetMyWorksOfTodayResponseFromJSONTyped(json, false);
}

export function GetMyWorksOfTodayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMyWorksOfTodayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'myWorkId': json['myWorkId'] == null ? undefined : json['myWorkId'],
        'myCropName': json['myCropName'] == null ? undefined : json['myCropName'],
        'myWorkName': json['myWorkName'] == null ? undefined : json['myWorkName'],
        'workTime': json['workTime'] == null ? undefined : json['workTime'],
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
    };
}

export function GetMyWorksOfTodayResponseToJSON(json: any): GetMyWorksOfTodayResponse {
    return GetMyWorksOfTodayResponseToJSONTyped(json, false);
}

export function GetMyWorksOfTodayResponseToJSONTyped(value?: GetMyWorksOfTodayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'myWorkId': value['myWorkId'],
        'myCropName': value['myCropName'],
        'myWorkName': value['myWorkName'],
        'workTime': value['workTime'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
    };
}

