/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WorkCardData } from '../models/WorkCardData';

export class GetMyWorksOfWeeklyResponse {
    'date'?: string;
    'workCardData'?: Array<WorkCardData>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "workCardData",
            "baseName": "workCardData",
            "type": "Array<WorkCardData>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetMyWorksOfWeeklyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
