/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetMyWorksOfTodayResponse {
    'myWorkId'?: number;
    'myCropName'?: string;
    'myWorkName'?: string;
    'workTime'?: string;
    'startTime'?: string;
    'endTime'?: string;
    'status'?: GetMyWorksOfTodayResponseStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "myWorkId",
            "baseName": "myWorkId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "myCropName",
            "baseName": "myCropName",
            "type": "string",
            "format": ""
        },
        {
            "name": "myWorkName",
            "baseName": "myWorkName",
            "type": "string",
            "format": ""
        },
        {
            "name": "workTime",
            "baseName": "workTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "GetMyWorksOfTodayResponseStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetMyWorksOfTodayResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export const GetMyWorksOfTodayResponseStatusEnum = {
  Completed: 'COMPLETED',
  Incompleted: 'INCOMPLETED'
} as const;
export type GetMyWorksOfTodayResponseStatusEnum = typeof GetMyWorksOfTodayResponseStatusEnum[keyof typeof GetMyWorksOfTodayResponseStatusEnum];

