/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetMyCropsResponse {
    'myCropId'?: number;
    'myCropName'?: string;
    'daysFromStartDate'?: number;
    'lifeCycle'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "myCropId",
            "baseName": "myCropId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "myCropName",
            "baseName": "myCropName",
            "type": "string",
            "format": ""
        },
        {
            "name": "daysFromStartDate",
            "baseName": "daysFromStartDate",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "lifeCycle",
            "baseName": "lifeCycle",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetMyCropsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
