/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MyCropCard } from '../models/MyCropCard';
import { PestCard } from '../models/PestCard';

export class GetPestCardListResponse {
    'pestRisks'?: Array<PestCard>;
    'myCrops'?: Array<MyCropCard>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pestRisks",
            "baseName": "pestRisks",
            "type": "Array<PestCard>",
            "format": ""
        },
        {
            "name": "myCrops",
            "baseName": "myCrops",
            "type": "Array<MyCropCard>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetPestCardListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
