/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TemperaturePerTime } from '../models/TemperaturePerTime';

export class GetTemperatureResponse {
    'maxTemperature'?: number;
    'minTemperature'?: number;
    'temperaturePerTime'?: Array<TemperaturePerTime>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maxTemperature",
            "baseName": "maxTemperature",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "minTemperature",
            "baseName": "minTemperature",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "temperaturePerTime",
            "baseName": "temperaturePerTime",
            "type": "Array<TemperaturePerTime>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetTemperatureResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
