/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetWeatherBriefingResponse {
    'hasWeatherRisk'?: boolean;
    'weatherMsg'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasWeatherRisk",
            "baseName": "hasWeatherRisk",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "weatherMsg",
            "baseName": "weatherMsg",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetWeatherBriefingResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
