/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValuePerTime } from '../models/ValuePerTime';

export class GetWeatherGraphResponse {
    'max'?: number;
    'min'?: number;
    'weatherMetric'?: GetWeatherGraphResponseWeatherMetricEnum;
    'valuePerTime'?: Array<ValuePerTime>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "max",
            "baseName": "max",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "weatherMetric",
            "baseName": "weatherMetric",
            "type": "GetWeatherGraphResponseWeatherMetricEnum",
            "format": ""
        },
        {
            "name": "valuePerTime",
            "baseName": "valuePerTime",
            "type": "Array<ValuePerTime>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetWeatherGraphResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export const GetWeatherGraphResponseWeatherMetricEnum = {
  Percipitation: 'PERCIPITATION',
  Temperature: 'TEMPERATURE',
  Humidity: 'HUMIDITY',
  WindSpeed: 'WIND_SPEED'
} as const;
export type GetWeatherGraphResponseWeatherMetricEnum = typeof GetWeatherGraphResponseWeatherMetricEnum[keyof typeof GetWeatherGraphResponseWeatherMetricEnum];

