/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWeatherBriefing
 */
export interface GetWeatherBriefing {
    /**
     * 
     * @type {boolean}
     * @memberof GetWeatherBriefing
     */
    hasWeatherRisk?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetWeatherBriefing
     */
    weatherMsg?: string;
}

/**
 * Check if a given object implements the GetWeatherBriefing interface.
 */
export function instanceOfGetWeatherBriefing(value: object): value is GetWeatherBriefing {
    return true;
}

export function GetWeatherBriefingFromJSON(json: any): GetWeatherBriefing {
    return GetWeatherBriefingFromJSONTyped(json, false);
}

export function GetWeatherBriefingFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWeatherBriefing {
    if (json == null) {
        return json;
    }
    return {
        
        'hasWeatherRisk': json['hasWeatherRisk'] == null ? undefined : json['hasWeatherRisk'],
        'weatherMsg': json['weatherMsg'] == null ? undefined : json['weatherMsg'],
    };
}

export function GetWeatherBriefingToJSON(json: any): GetWeatherBriefing {
    return GetWeatherBriefingToJSONTyped(json, false);
}

export function GetWeatherBriefingToJSONTyped(value?: GetWeatherBriefing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasWeatherRisk': value['hasWeatherRisk'],
        'weatherMsg': value['weatherMsg'],
    };
}

