/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetWindInfoResponse {
    'direction'?: string;
    'degree'?: number;
    'speed'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "direction",
            "baseName": "direction",
            "type": "string",
            "format": ""
        },
        {
            "name": "degree",
            "baseName": "degree",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "speed",
            "baseName": "speed",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return GetWindInfoResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
