/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetWeatherConditionResponse {
    'weatherCondition'?: string;
    'weatherKeyword'?: string;
    'temperature'?: number;
    'memberName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "weatherCondition",
            "baseName": "weatherCondition",
            "type": "string",
            "format": ""
        },
        {
            "name": "weatherKeyword",
            "baseName": "weatherKeyword",
            "type": "string",
            "format": ""
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "memberName",
            "baseName": "memberName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetWeatherConditionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
