/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWeatherCondition
 */
export interface GetWeatherCondition {
    /**
     * 
     * @type {string}
     * @memberof GetWeatherCondition
     */
    weatherCondition?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWeatherCondition
     */
    weatherKeyword?: string;
    /**
     * 
     * @type {number}
     * @memberof GetWeatherCondition
     */
    temperature?: number;
}

/**
 * Check if a given object implements the GetWeatherCondition interface.
 */
export function instanceOfGetWeatherCondition(value: object): value is GetWeatherCondition {
    return true;
}

export function GetWeatherConditionFromJSON(json: any): GetWeatherCondition {
    return GetWeatherConditionFromJSONTyped(json, false);
}

export function GetWeatherConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWeatherCondition {
    if (json == null) {
        return json;
    }
    return {
        
        'weatherCondition': json['weatherCondition'] == null ? undefined : json['weatherCondition'],
        'weatherKeyword': json['weatherKeyword'] == null ? undefined : json['weatherKeyword'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
    };
}

export function GetWeatherConditionToJSON(json: any): GetWeatherCondition {
    return GetWeatherConditionToJSONTyped(json, false);
}

export function GetWeatherConditionToJSONTyped(value?: GetWeatherCondition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weatherCondition': value['weatherCondition'],
        'weatherKeyword': value['weatherKeyword'],
        'temperature': value['temperature'],
    };
}

