/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModifyMyWorkResponse
 */
export interface ModifyMyWorkResponse {
    /**
     * 
     * @type {number}
     * @memberof ModifyMyWorkResponse
     */
    myWorkId?: number;
}

/**
 * Check if a given object implements the ModifyMyWorkResponse interface.
 */
export function instanceOfModifyMyWorkResponse(value: object): value is ModifyMyWorkResponse {
    return true;
}

export function ModifyMyWorkResponseFromJSON(json: any): ModifyMyWorkResponse {
    return ModifyMyWorkResponseFromJSONTyped(json, false);
}

export function ModifyMyWorkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyMyWorkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'myWorkId': json['myWorkId'] == null ? undefined : json['myWorkId'],
    };
}

export function ModifyMyWorkResponseToJSON(json: any): ModifyMyWorkResponse {
    return ModifyMyWorkResponseToJSONTyped(json, false);
}

export function ModifyMyWorkResponseToJSONTyped(value?: ModifyMyWorkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'myWorkId': value['myWorkId'],
    };
}

