/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ModifyMyWorkResponse {
    'myWorkId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "myWorkId",
            "baseName": "myWorkId",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ModifyMyWorkResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
