/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModifyMyWorkRequest
 */
export interface ModifyMyWorkRequest {
    /**
     * 
     * @type {number}
     * @memberof ModifyMyWorkRequest
     */
    myWorkId: number;
    /**
     * 
     * @type {Date}
     * @memberof ModifyMyWorkRequest
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof ModifyMyWorkRequest
     */
    endTime: Date;
}

/**
 * Check if a given object implements the ModifyMyWorkRequest interface.
 */
export function instanceOfModifyMyWorkRequest(value: object): value is ModifyMyWorkRequest {
    if (!('myWorkId' in value) || value['myWorkId'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    return true;
}

export function ModifyMyWorkRequestFromJSON(json: any): ModifyMyWorkRequest {
    return ModifyMyWorkRequestFromJSONTyped(json, false);
}

export function ModifyMyWorkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyMyWorkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'myWorkId': json['myWorkId'],
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
    };
}

export function ModifyMyWorkRequestToJSON(json: any): ModifyMyWorkRequest {
    return ModifyMyWorkRequestToJSONTyped(json, false);
}

export function ModifyMyWorkRequestToJSONTyped(value?: ModifyMyWorkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'myWorkId': value['myWorkId'],
        'startTime': ((value['startTime']).toISOString()),
        'endTime': ((value['endTime']).toISOString()),
    };
}

