/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyCropResponse
 */
export interface MyCropResponse {
    /**
     * 
     * @type {number}
     * @memberof MyCropResponse
     */
    myCropId?: number;
    /**
     * 
     * @type {string}
     * @memberof MyCropResponse
     */
    myCropName?: string;
}

/**
 * Check if a given object implements the MyCropResponse interface.
 */
export function instanceOfMyCropResponse(value: object): value is MyCropResponse {
    return true;
}

export function MyCropResponseFromJSON(json: any): MyCropResponse {
    return MyCropResponseFromJSONTyped(json, false);
}

export function MyCropResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyCropResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'myCropId': json['myCropId'] == null ? undefined : json['myCropId'],
        'myCropName': json['myCropName'] == null ? undefined : json['myCropName'],
    };
}

export function MyCropResponseToJSON(json: any): MyCropResponse {
    return MyCropResponseToJSONTyped(json, false);
}

export function MyCropResponseToJSONTyped(value?: MyCropResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'myCropId': value['myCropId'],
        'myCropName': value['myCropName'],
    };
}

