/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecommendedWorksResponse
 */
export interface RecommendedWorksResponse {
    /**
     * 
     * @type {number}
     * @memberof RecommendedWorksResponse
     */
    workId?: number;
    /**
     * 
     * @type {string}
     * @memberof RecommendedWorksResponse
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof RecommendedWorksResponse
     */
    endTime?: string;
    /**
     * 
     * @type {string}
     * @memberof RecommendedWorksResponse
     */
    recommendation?: string;
    /**
     * 
     * @type {number}
     * @memberof RecommendedWorksResponse
     */
    neighborCount?: number;
}

/**
 * Check if a given object implements the RecommendedWorksResponse interface.
 */
export function instanceOfRecommendedWorksResponse(value: object): value is RecommendedWorksResponse {
    return true;
}

export function RecommendedWorksResponseFromJSON(json: any): RecommendedWorksResponse {
    return RecommendedWorksResponseFromJSONTyped(json, false);
}

export function RecommendedWorksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendedWorksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workId': json['workId'] == null ? undefined : json['workId'],
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'recommendation': json['recommendation'] == null ? undefined : json['recommendation'],
        'neighborCount': json['neighborCount'] == null ? undefined : json['neighborCount'],
    };
}

export function RecommendedWorksResponseToJSON(json: any): RecommendedWorksResponse {
    return RecommendedWorksResponseToJSONTyped(json, false);
}

export function RecommendedWorksResponseToJSONTyped(value?: RecommendedWorksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workId': value['workId'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'recommendation': value['recommendation'],
        'neighborCount': value['neighborCount'],
    };
}

