/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RecommendationDurations } from '../models/RecommendationDurations';

export class RecommendedWorksResponse {
    'workName'?: string;
    'workId'?: number;
    'neighborCount'?: number;
    'recommendationDurations'?: Array<RecommendationDurations>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "workName",
            "baseName": "workName",
            "type": "string",
            "format": ""
        },
        {
            "name": "workId",
            "baseName": "workId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "neighborCount",
            "baseName": "neighborCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "recommendationDurations",
            "baseName": "recommendationDurations",
            "type": "Array<RecommendationDurations>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RecommendedWorksResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
