/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecommendedWorksResponse } from './RecommendedWorksResponse';
import {
    RecommendedWorksResponseFromJSON,
    RecommendedWorksResponseFromJSONTyped,
    RecommendedWorksResponseToJSON,
    RecommendedWorksResponseToJSONTyped,
} from './RecommendedWorksResponse';
import type { MyCropResponse } from './MyCropResponse';
import {
    MyCropResponseFromJSON,
    MyCropResponseFromJSONTyped,
    MyCropResponseToJSON,
    MyCropResponseToJSONTyped,
} from './MyCropResponse';

/**
 * 
 * @export
 * @interface RecommendWorksResponse
 */
export interface RecommendWorksResponse {
    /**
     * 
     * @type {Array<RecommendedWorksResponse>}
     * @memberof RecommendWorksResponse
     */
    recommendedWorks?: Array<RecommendedWorksResponse>;
    /**
     * 
     * @type {Array<MyCropResponse>}
     * @memberof RecommendWorksResponse
     */
    myCrops?: Array<MyCropResponse>;
}

/**
 * Check if a given object implements the RecommendWorksResponse interface.
 */
export function instanceOfRecommendWorksResponse(value: object): value is RecommendWorksResponse {
    return true;
}

export function RecommendWorksResponseFromJSON(json: any): RecommendWorksResponse {
    return RecommendWorksResponseFromJSONTyped(json, false);
}

export function RecommendWorksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendWorksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'recommendedWorks': json['recommendedWorks'] == null ? undefined : ((json['recommendedWorks'] as Array<any>).map(RecommendedWorksResponseFromJSON)),
        'myCrops': json['myCrops'] == null ? undefined : ((json['myCrops'] as Array<any>).map(MyCropResponseFromJSON)),
    };
}

export function RecommendWorksResponseToJSON(json: any): RecommendWorksResponse {
    return RecommendWorksResponseToJSONTyped(json, false);
}

export function RecommendWorksResponseToJSONTyped(value?: RecommendWorksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recommendedWorks': value['recommendedWorks'] == null ? undefined : ((value['recommendedWorks'] as Array<any>).map(RecommendedWorksResponseToJSON)),
        'myCrops': value['myCrops'] == null ? undefined : ((value['myCrops'] as Array<any>).map(MyCropResponseToJSON)),
    };
}

