/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterMyWorkRequest
 */
export interface RegisterMyWorkRequest {
    /**
     * 
     * @type {number}
     * @memberof RegisterMyWorkRequest
     */
    recommendedWorkId: number;
    /**
     * 
     * @type {number}
     * @memberof RegisterMyWorkRequest
     */
    myCropId: number;
    /**
     * 
     * @type {Date}
     * @memberof RegisterMyWorkRequest
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof RegisterMyWorkRequest
     */
    endTime: Date;
}

/**
 * Check if a given object implements the RegisterMyWorkRequest interface.
 */
export function instanceOfRegisterMyWorkRequest(value: object): value is RegisterMyWorkRequest {
    if (!('recommendedWorkId' in value) || value['recommendedWorkId'] === undefined) return false;
    if (!('myCropId' in value) || value['myCropId'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    return true;
}

export function RegisterMyWorkRequestFromJSON(json: any): RegisterMyWorkRequest {
    return RegisterMyWorkRequestFromJSONTyped(json, false);
}

export function RegisterMyWorkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterMyWorkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recommendedWorkId': json['recommendedWorkId'],
        'myCropId': json['myCropId'],
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
    };
}

export function RegisterMyWorkRequestToJSON(json: any): RegisterMyWorkRequest {
    return RegisterMyWorkRequestToJSONTyped(json, false);
}

export function RegisterMyWorkRequestToJSONTyped(value?: RegisterMyWorkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recommendedWorkId': value['recommendedWorkId'],
        'myCropId': value['myCropId'],
        'startTime': ((value['startTime']).toISOString()),
        'endTime': ((value['endTime']).toISOString()),
    };
}

