/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterMyWorkResponse
 */
export interface RegisterMyWorkResponse {
    /**
     * 
     * @type {number}
     * @memberof RegisterMyWorkResponse
     */
    workId?: number;
}

/**
 * Check if a given object implements the RegisterMyWorkResponse interface.
 */
export function instanceOfRegisterMyWorkResponse(value: object): value is RegisterMyWorkResponse {
    return true;
}

export function RegisterMyWorkResponseFromJSON(json: any): RegisterMyWorkResponse {
    return RegisterMyWorkResponseFromJSONTyped(json, false);
}

export function RegisterMyWorkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterMyWorkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workId': json['workId'] == null ? undefined : json['workId'],
    };
}

export function RegisterMyWorkResponseToJSON(json: any): RegisterMyWorkResponse {
    return RegisterMyWorkResponseToJSONTyped(json, false);
}

export function RegisterMyWorkResponseToJSONTyped(value?: RegisterMyWorkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workId': value['workId'],
    };
}

