/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class UpdateMyWorkStatusRequest {
    'myWorkId'?: number;
    'status'?: UpdateMyWorkStatusRequestStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "myWorkId",
            "baseName": "myWorkId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UpdateMyWorkStatusRequestStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateMyWorkStatusRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export const UpdateMyWorkStatusRequestStatusEnum = {
  Completed: 'COMPLETED',
  Incompleted: 'INCOMPLETED'
} as const;
export type UpdateMyWorkStatusRequestStatusEnum = typeof UpdateMyWorkStatusRequestStatusEnum[keyof typeof UpdateMyWorkStatusRequestStatusEnum];

