/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValuePerTime
 */
export interface ValuePerTime {
    /**
     * 
     * @type {string}
     * @memberof ValuePerTime
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ValuePerTime
     */
    value?: number;
}

/**
 * Check if a given object implements the ValuePerTime interface.
 */
export function instanceOfValuePerTime(value: object): value is ValuePerTime {
    return true;
}

export function ValuePerTimeFromJSON(json: any): ValuePerTime {
    return ValuePerTimeFromJSONTyped(json, false);
}

export function ValuePerTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValuePerTime {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function ValuePerTimeToJSON(json: any): ValuePerTime {
    return ValuePerTimeToJSONTyped(json, false);
}

export function ValuePerTimeToJSONTyped(value?: ValuePerTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

