/* tslint:disable */
/* eslint-disable */
/**
 * Nyeoreumnagi Swagger
 * 녀름나기 REST API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeatherRiskDto
 */
export interface WeatherRiskDto {
    /**
     * 
     * @type {string}
     * @memberof WeatherRiskDto
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof WeatherRiskDto
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof WeatherRiskDto
     */
    endTime?: string;
}

/**
 * Check if a given object implements the WeatherRiskDto interface.
 */
export function instanceOfWeatherRiskDto(value: object): value is WeatherRiskDto {
    return true;
}

export function WeatherRiskDtoFromJSON(json: any): WeatherRiskDto {
    return WeatherRiskDtoFromJSONTyped(json, false);
}

export function WeatherRiskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherRiskDto {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
    };
}

export function WeatherRiskDtoToJSON(json: any): WeatherRiskDto {
    return WeatherRiskDtoToJSONTyped(json, false);
}

export function WeatherRiskDtoToJSONTyped(value?: WeatherRiskDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
    };
}

