name: 투표
description: 프로젝트와 관련된 의사결정을 위해 투표를 진행합니다.
title: "[투표] "
labels: ["투표"]
body:
  - type: textarea
    id: question
    attributes:
      label: 투표 주제
      description: 투표할 주제를 간단하게 적어주세요.
      placeholder: 예) 다음 개발 우선순위
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: 투표 옵션
      description: 선택지를 각 줄마다 하나씩 입력해주세요.
      placeholder: |
        옵션 1
        옵션 2
        옵션 3