export const WEATHER_METRICS = {
  PRECIPITATION: 'PERCIPITATION',
  TEMPERATURE: 'TEMPERATURE',
  HUMIDITY: 'HUMIDITY',
  WIND_SPEED: 'WIND_SPEED',
} as const;

export type WeatherMetrics =
  (typeof WEATHER_METRICS)[keyof typeof WEATHER_METRICS];

export const WEATHER_CONDITIONS = {
  SUNNY: 'SUNNY',
  LESS_CLOUDY: 'LESS_CLOUDY',
  CLOUDY: 'CLOUDY',
  STRONG_WIND: 'STRONG_WIND',
  THUNDER: 'THUNDER',
  RAIN: 'RAIN',
  HEAVY_RAIN: 'HEAVY_RAIN',
  SNOW: 'SNOW',
  NIGHT: 'NIGHT',
  CLOUDY_NIGHT: 'CLOUDY_NIGHT',
} as const;

export type WeatherConditionsType =
  (typeof WEATHER_CONDITIONS)[keyof typeof WEATHER_CONDITIONS];

export const WEATHER_DAMAGES = {
  SUNBURN: 'SUNBURN',
  WATER_DEFFICIENCY: 'WATER_DEFFICIENCY',
  POOR_COLORING: 'POOR_COLORING',
  FRUIT_CRAKING: 'FRUIT_CRAKING',
  FRUIT_DROP: 'FRUIT_DROP',
  FLOWER_DROP: 'FLOWER_DROP',
} as const;

export type WeatherDamagesType =
  (typeof WEATHER_DAMAGES)[keyof typeof WEATHER_DAMAGES];
